### ISSUE TITLE
Two braches

### ISSUE THREAD

**Issue by buehlmannjan** [UniLuFS2020-ReplicationSeminar/data-mining-ce2#2]
https://github.com/UniLuFS2020-ReplicationSeminar/data-mining-ce2/blob/a130c4daa4224bdab407cf326ead4c8a9d2cc615/scripts/01_corpus-of-articles.R#L19

@ursulinakoelbener I just saw that we are working on two different scripts now. How are we going to solve this? 😂

**Comment by ursulinakoelbener** [comment]
solved manually
